# Generated by Django 4.2 on 2023-04-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, verbose_name='Эл. Почта')),
                ('prof', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИ')),
                ('prof', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Уровень обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='формат')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Номер')),
                ('title', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255, verbose_name='Знание языка')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название школы')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=255, verbose_name='Название силлабуса')),
                ('total_hours', models.IntegerField(null=True, verbose_name='Всего часов')),
                ('classroom_hours', models.IntegerField(null=True, verbose_name='Классных часов')),
                ('semester', models.IntegerField(null=True, verbose_name='Семестр')),
                ('ects', models.IntegerField(null=True, verbose_name='ects кредиты')),
                ('iw_hours', models.IntegerField(null=True, verbose_name='СРОП часов')),
                ('prerequisites', models.TextField(verbose_name='Пререквизиты')),
                ('edu_programms', models.TextField(verbose_name='Образовательные программы')),
                ('time_place', models.TextField(verbose_name='Время и место проведения')),
                ('course_objective', models.TextField(verbose_name='Цель курса')),
                ('document', models.FileField(null=True, upload_to='', verbose_name='Файл')),
                ('course_philosophy', models.TextField(verbose_name='Философия курса')),
                ('course_etics', models.TextField(verbose_name='Политика курса')),
                ('asu', models.BooleanField(default=0, verbose_name='На основе ASU')),
                ('agreed_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.director')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.course')),
                ('format_of_training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.format')),
                ('instructor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.customuser')),
                ('language_of_education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.language')),
                ('proficiency_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.proficiency')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.status')),
                ('training_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.edulevel')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(null=True, verbose_name='Неделя')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('tasks', models.TextField(verbose_name='Задания')),
                ('course_lo', models.TextField(verbose_name='Результаты обучения')),
                ('questions', models.TextField(verbose_name='Вопросы по модулю')),
                ('literature', models.TextField(blank=True, verbose_name='Литература')),
                ('grading', models.TextField(verbose_name='Оценивание')),
                ('max_percent', models.IntegerField(null=True, verbose_name='Максимальный процент')),
                ('max_weight', models.IntegerField(null=True, verbose_name='Максимальный вес')),
                ('total_in_points', models.IntegerField(null=True, verbose_name='В баллах')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.format')),
                ('syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.syllabus')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.school'),
        ),
    ]
