# Generated by Django 4.2 on 2023-04-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0002_literature_course_alter_syllabus_agreed_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='number',
        ),
    ]
