# Generated by Django 4.2 on 2023-04-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0003_remove_literature_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureInSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=0, verbose_name='Обязательная')),
                ('literature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.literature', verbose_name='Литература')),
                ('syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.syllabus', verbose_name='Силлабус')),
            ],
        ),
    ]
