# Generated by Django 4.2 on 2023-05-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0005_alter_module_literature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=0, verbose_name='Тип РО')),
                ('info', models.TextField(verbose_name='Результаты обучения')),
                ('syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabuses.syllabus', verbose_name='Силлабус')),
            ],
        ),
    ]
