# Generated by Django 4.2.2 on 2023-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabuses', '0007_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
    ]
